#!/usr/bin/env python3
"""
Build the WIEMIP docs site: `docs/*.md` -> Read-the-Docs-style static pages.

    uv run --with markdown python docs/build_docs.py

Markdown is the source of truth; the generated `.html` is committed so GitHub Pages
(which serves this repo as-is, `.nojekyll`) needs no build step. Edit the markdown,
re-run this, commit both.

Layout of a built page: a persistent left sidebar listing every page in NAV, with the
*current* page expanded to its own section headings, and the content in the column
beside it — the familiar Sphinx/RTD shape. Prev/next links and breadcrumbs come from
NAV order, so adding a page is a one-line change.

    docs/index.md   -> docs/index.html          served at /docs/
    docs/<slug>.md  -> docs/<slug>/index.html   served at /docs/<slug>/

Per-page metadata is a header block at the top of each markdown file (python-markdown's
`meta` extension):

    Title: WIEMIP · Reading data          # browser tab / search result
    Nav: Reading data                     # sidebar label (defaults to Title)
    Description: One sentence.            # <meta description>

To add a page: write `docs/<slug>.md`, add its slug to NAV, rebuild.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

try:
    import markdown
except ModuleNotFoundError:  # keep the fix in the error, not in a wiki somewhere
    sys.exit(
        "This script needs python-markdown. Run it as:\n"
        "    uv run --with markdown python docs/build_docs.py"
    )

# --- edit me ---------------------------------------------------------------
SITE_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = SITE_ROOT / "docs"

# Sidebar order. Every entry is a `docs/<slug>.md`; `index` is the landing page.
NAV = [
    "overview",
    "quickstart",
    "reading-data",
    "factorials",
    "examples",
    "adding-a-model",
    "caveats",
]

PROJECT = "wiemip_registry"
PROJECT_TAGLINE = "WIEMIP submission reader"
# Links pinned to the bottom of the sidebar.
SIDEBAR_LINKS = [
    ("API reference", "/docs/api/"),  # generated by pdoc, see docs/build_api.sh
    ("JupyterHub", "https://wiemip-hub.org/"),
    ("Source (GitHub)", "https://github.com/WIEMIP/wiemip-data-registry"),
    ("Issues", "https://github.com/WIEMIP/wiemip-data-registry/issues"),
]

DEFAULT_TITLE = "WIEMIP · Docs"
DEFAULT_DESCRIPTION = "Documentation for the WIEMIP data tooling."
# `extra` brings fenced code blocks + tables + attribute lists; `toc` adds heading
# ids (so the sidebar section links and deep links work); `meta` reads the header
# block; `sane_lists` stops a numbered list swallowing the paragraph after it.
EXTENSIONS = ["extra", "toc", "sane_lists", "meta"]
EXTENSION_CONFIGS = {"toc": {"permalink": "#", "toc_depth": "2-3"}}
# ---------------------------------------------------------------------------

TEMPLATE = """<!doctype html>
<!-- GENERATED from docs/{source_name} by docs/build_docs.py — edit the markdown, not this file. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <meta name="description" content="{description}">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16.png">
  <link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
  <link rel="stylesheet" href="/assets/styles.css">
</head>
<body class="docs-body">
  <!-- CSS-only sidebar toggle for narrow screens; the only JS is search. -->
  <input type="checkbox" id="docs-nav-toggle" class="docs-nav-toggle" hidden>
  <div class="docs-shell">
    <aside class="docs-sidebar">
      <a class="docs-brand" href="/">
        <span class="docs-brand-mark">W</span>
        <span>
          <strong>{project}</strong>
          <small>{tagline}</small>
        </span>
      </a>
      <label class="docs-nav-close" for="docs-nav-toggle" aria-label="Close navigation">✕</label>
      <div class="docs-search-wrap">
        <input type="search" id="docs-search" class="docs-search" placeholder="Search docs (/)"
               autocomplete="off" spellcheck="false" aria-label="Search documentation">
        <ul id="docs-search-results" class="docs-search-results" hidden></ul>
      </div>
{nav}
      <div class="docs-sidebar-links">
{sidebar_links}
      </div>
    </aside>

    <div class="docs-main">
      <div class="docs-topbar">
        <label class="docs-burger" for="docs-nav-toggle" aria-label="Open navigation">☰</label>
        <nav class="docs-crumbs" aria-label="Breadcrumb">
          <a href="/">WIEMIP</a> <span>›</span> <a href="/docs/">Docs</a>{crumb_tail}
        </nav>
      </div>

      <article class="doc">
{body}
      </article>

{sequence}
      <footer class="docs-foot">
        WIEMIP · <a href="https://github.com/WIEMIP">github.com/WIEMIP</a>
      </footer>
    </div>
  </div>
  <label class="docs-scrim" for="docs-nav-toggle" aria-hidden="true"></label>
  <script src="/assets/docs-search.js" defer></script>
</body>
</html>
"""


@dataclass
class Page:
    slug: str
    source: Path
    title: str = ""  # browser title
    heading: str = ""  # sidebar / breadcrumb label
    description: str = ""
    body: str = ""
    toc: list = field(default_factory=list)  # python-markdown toc_tokens

    @property
    def url(self) -> str:
        return f"/docs/{self.slug}/"

    @property
    def out_path(self) -> Path:
        # Never docs/index.html — that is the hand-written redirect to /docs/api/.
        return DOCS_DIR / self.slug / "index.html"


def _first(meta: dict, key: str, fallback: str = "") -> str:
    """python-markdown's `meta` gives {key: [line, ...]}; we want one line."""
    values = meta.get(key) or []
    return " ".join(values).strip() or fallback


def _indent(html: str, spaces: int) -> str:
    """Indent for readability of the generated source. NEVER use this on the page
    body: `<pre>` preserves whitespace, so indenting would prepend the padding to
    every line of every code sample."""
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in html.splitlines())


def parse(slug: str) -> Page:
    source = DOCS_DIR / f"{slug}.md"
    if not source.is_file():
        sys.exit(f"NAV lists '{slug}' but {source} does not exist.")

    text = source.read_text()
    md = markdown.Markdown(extensions=EXTENSIONS, extension_configs=EXTENSION_CONFIGS)
    page = Page(slug=slug, source=source)
    page.body = md.convert(text)
    meta = getattr(md, "Meta", {})
    page.title = _first(meta, "title", DEFAULT_TITLE)
    # Sidebar label: `Nav:` if given, else the page's own `# ` heading, else the title.
    h1 = next(
        (line[2:].strip() for line in text.splitlines() if line.startswith("# ")), ""
    )
    page.heading = _first(meta, "nav", h1 or page.title)
    page.description = _first(meta, "description", DEFAULT_DESCRIPTION)
    # `toc_depth: 2-3` excludes the h1, so toc_tokens is already the h2 level with
    # any h3s as children — exactly what the sidebar branch wants.
    page.toc = md.toc_tokens
    return page


SEARCH_INDEX = DOCS_DIR / "search-index.json"
_TAG = re.compile(r"<[^>]+>")
_SECTION = re.compile(r'<h([23]) id="([^"]+)"[^>]*>(.*?)</h\1>', re.S)


def index_entries(page: Page) -> list[dict]:
    """One search entry per h2/h3 section, so a hit lands on the heading. Text is the
    rendered HTML with tags stripped — cheap, and it means code samples are searchable
    too (searching `.read()` should find the section that demonstrates it)."""
    entries = [{"u": page.url, "a": "", "p": page.heading, "h": page.heading,
                "t": _clean(page.body)[:400]}]
    marks = list(_SECTION.finditer(page.body))
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(page.body)
        name = _clean(m.group(3)).removesuffix("#").strip()
        entries.append({
            "u": page.url,
            "a": f"#{m.group(2)}",
            "p": page.heading,
            "h": name,
            "t": _clean(page.body[m.end():end])[:400],
        })
    return entries


def _clean(html: str) -> str:
    return " ".join(_TAG.sub(" ", html).split())


def _section_list(tokens: list, depth: int = 0) -> str:
    """The current page's headings, nested — the expanded branch of the sidebar."""
    if not tokens or depth > 1:  # h2 + h3 only; deeper headings would be noise
        return ""
    items = []
    for token in tokens:
        children = _section_list(token.get("children") or [], depth + 1)
        items.append(
            f'<li><a href="#{token["id"]}">{token["name"]}</a>{children}</li>'
        )
    return '<ul class="docs-nav-sections">' + "".join(items) + "</ul>"


def render_nav(pages: list[Page], current: Page) -> str:
    """Sidebar: every page, with the current one expanded to its sections."""
    items = []
    for page in pages:
        classes = ' class="current"' if page is current else ""
        sections = _section_list(page.toc) if page is current else ""
        items.append(
            f"<li{classes}><a href=\"{page.url}\">{page.heading}</a>{sections}</li>"
        )
    inner = "\n".join(items)
    return (
        '<nav class="docs-nav" aria-label="Documentation">\n'
        '<ul class="docs-nav-pages">\n' + inner + "\n</ul>\n</nav>"
    )


def render_sequence(pages: list[Page], current: Page) -> str:
    """Prev/next footer links, RTD-style, driven by NAV order."""
    index = pages.index(current)
    previous = pages[index - 1] if index > 0 else None
    following = pages[index + 1] if index < len(pages) - 1 else None
    if not previous and not following:
        return ""
    parts = ['      <nav class="docs-seq" aria-label="Page navigation">']
    if previous:
        parts.append(
            f'        <a class="docs-seq-prev" href="{previous.url}">'
            f"<small>Previous</small>{previous.heading}</a>"
        )
    if following:
        parts.append(
            f'        <a class="docs-seq-next" href="{following.url}">'
            f"<small>Next</small>{following.heading}</a>"
        )
    parts.append("      </nav>\n")
    return "\n".join(parts)


def build(pages: list[Page], page: Page) -> Path:
    crumb_tail = "" if page.slug == "index" else f" <span>›</span> {page.heading}"
    sidebar_links = "\n".join(
        f'        <a href="{href}">{label}</a>' for label, href in SIDEBAR_LINKS
    )
    html = TEMPLATE.format(
        source_name=page.source.name,
        title=page.title,
        description=page.description,
        project=PROJECT,
        tagline=PROJECT_TAGLINE,
        nav=_indent(render_nav(pages, page), 6),
        sidebar_links=sidebar_links,
        crumb_tail=crumb_tail,
        body=page.body,  # flush left on purpose — see _indent()
        sequence=render_sequence(pages, page),
    )
    page.out_path.parent.mkdir(parents=True, exist_ok=True)
    page.out_path.write_text(html)
    return page.out_path


def main(argv: list[str]) -> None:
    # Every page is parsed regardless of what's being rebuilt: the sidebar on any
    # one page needs every other page's title.
    pages = [parse(slug) for slug in NAV]

    stray = {p.stem for p in DOCS_DIR.glob("*.md")} - set(NAV)
    if stray:
        print(f"note: not in NAV, so not built: {', '.join(sorted(stray))}")

    wanted = [s.removesuffix(".md").strip("/") for s in argv] or NAV
    unknown = [s for s in wanted if s not in NAV]
    if unknown:
        sys.exit(f"Not in NAV: {', '.join(unknown)}")

    index: list[dict] = []
    for page in pages:
        index += index_entries(page)
    SEARCH_INDEX.write_text(json.dumps(index, separators=(",", ":")))
    print(f"{SEARCH_INDEX.relative_to(SITE_ROOT)}: {len(index)} sections indexed")

    for page in pages:
        if page.slug in wanted:
            print(f"{page.source.relative_to(SITE_ROOT)} -> "
                  f"{build(pages, page).relative_to(SITE_ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1:])
